#!/usr/bin/env bash

set -o errexit
set -o nounset

readonly THIS_CMD="${0##*/}"
readonly VERSION='1.3.2'
readonly PACMANS=(
	"paru"
	"yay"
	"pacman"
)

_version() {
	echo -e "$THIS_CMD -- v$VERSION
Released under the MIT License.
    https://github.com/sheepla/fzpac"
}

_help() {
	cat <<EOF
$THIS_CMD -- Arch Linux package finder with fzf

USAGE
    $THIS_CMD SUBCMD KEYWORDS...

SUBCMD
    s, select        SEARCH FOR: all available packages
                     RUN:        pacman -Ssq -> fzf
                     STDOUT:     only names of selected packages
    q, select-local  SEARCH FOR: already installed packages
                     RUN:        pacman -Qsq -> fzf
                     STDOUT:     only names of selected packages

    i, info          SEARCH FOR: all available packages
                     RUN:        pacman -Ssq -> fzf -> pacman -Sii
                     STDOUT:     detailed information on selected packages
    l, info-local    SEARCH FOR: already installed packages
                     RUN:        pacman -Qsq -> fzf -> pacman -Qil
                     STDOUT:     detailed information on selected packages

    b, browse        SEARCH FOR: all available packages
                     RUN:        pacman -Ssq -> fzf <--> pacman -Sii|less
                     STDOUT:     none
    v, browse-local  SEARCH FOR: already installed packages
                     RUN:        pacman -Qsq -> fzf <--> pacman -Qil|less
                     STDOUT:     none

    S, install       Select packages and INSTALL it.
                     SEARCH FOR: all available packages
                     RUN:        pacman -Ssq -> fzf -> sudo pacman -S

    R, remove        Select packages and UNINSTALL it.
                     SEARCH FOR: already installed packages
                     RUN:        pacman -Qsq -> fzf -> sudo pacman -Rn

    A, autoremove    Select packages that are no longer needed and UNINSTALL it.
                     SEARCH FOR: dependencies that are no longer needed
                     RUN:        pacman -Qdtq -> fzf -> sudo pacman -Rns

    h, help          Show this usage.
    V, version       Show version.

EOF
}

_test_cmd() {
    for cmd in "${@}"; do
        if ! command -v "${cmd}" &>/dev/null; then
            _err "${cmd} is not installed. please install it."
            return 1
        fi
    done
}

_pacman() {
	local _cmd
	for _cmd in "${PACMANS[@]}"; do
		if command -v "${_cmd}" &>/dev/null; then
			echo -n "${_cmd}"
			return 0
		fi
	done
	_err 'The command for pacman or AUR helper was not found.'
	exit 1
}

_fzf() {
	env LANG=C fzf "${@}"
}

_main() {
	if [[ $# -lt 1 ]]; then
		_help
		exit 0
	fi

	_test_cmd fzf || return 1

	local pacman_cmd
	pacman_cmd="$(_pacman)"

	for arg in "${@}"; do
		case "${arg}" in
		s | select)
			shift
			_select_from_all_pkgs "${pacman_cmd}" "${@}"
			break
			;;
		q | select-local)
			shift
			_select_from_local_pkgs "${pacman_cmd}" "${@}"
			break
			;;
		i | info)
			shift
			_select_from_all_pkgs "${pacman_cmd}" "${@}" | "${pacman_cmd}" --sync --info --info -
			break
			;;
		l | info-local)
			shift
			_select_from_local_pkgs "${pacman_cmd}" "${@}" | "${pacman_cmd}" --query --info --info -
			break
			;;
		b | browse)
			shift
			_browse_all_pkgs "${pacman_cmd}" "${@}"
			break
			;;
		v | browse-local)
			shift
			_browse_local_pkgs "${pacman_cmd}" "${@}"
			break
			;;
		S | install)
			shift
			if [ "${pacman_cmd}" = 'pacman' ]; then
				_select_from_all_pkgs pacman "${@}" | sudo pacman --sync -
			else
				_select_from_all_pkgs "${pacman_cmd}" "${@}" | "${pacman_cmd}" --sync -
			fi
			break
			;;
		R | remove)
			shift
			if [ "${pacman_cmd}" = 'pacman' ]; then
				_select_from_local_pkgs pacman "${@}" | sudo pacman --remove --nosave -
			else
				_select_from_local_pkgs "${pacman_cmd}" "${@}" | "${pacman_cmd}" --remove --nosave -
			fi
			break
			;;
		A | autoremove)
			shift
			if [ "${pacman_cmd}" = 'pacman' ]; then
				_select_from_non_required_pkgs "${pacman_cmd}" "${@}" | sudo pacman --remove --nosave --recursive -
			else
				_select_from_non_required_pkgs "${pacman_cmd}" "${@}" | "${pacman_cmd}" --remove --nosave --recursive -
			fi
			break
			;;
		h | -h | help | --help)
			_help
			break
			;;
		V | version | --version)
			_version
			break
			;;
		*)
			_err "Invalid sub command: $1."
			_help
			return 1
			;;
		esac
	done
}

_err() {
	echo -e "[ \e[31mERR\e[m ] ${*}" >&2
}

_select_from_all_pkgs() {
	local pacman_cmd="$1"
	shift
	"${pacman_cmd}" --sync --search --quiet "${@}" |
		_fzf --multi --preview "${pacman_cmd} --sync --info {}"
}

_select_from_local_pkgs() {
	local pacman_cmd="$1"
	shift
	"${pacman_cmd}" --query --search --quiet "${@}" |
		_fzf --multi --preview "${pacman_cmd} --query --info --list {}"
}

_select_from_non_required_pkgs() {
	local pacman_cmd="$1"
	shift
	"${pacman_cmd}" --query --deps --unrequired --quiet "${@}" |
		_fzf --multi --preview "${pacman_cmd} --query --info --list {}"
}

_browse_all_pkgs() {
	local pacman_cmd="$1"
	shift
	"${pacman_cmd}" --sync --search --quiet "${@}" |
		_fzf --preview "${pacman_cmd} --sync --info {}" \
			--bind "enter:execute(${pacman_cmd} --sync --info --info {} | less)"
}

_browse_local_pkgs() {
	local pacman_cmd="$1"
	shift
	"${pacman_cmd}" -Qsq "${@}" |
		_fzf --preview "${pacman_cmd} --query --info --list {}" \
			--bind "enter:execute(${pacman_cmd} --query --info --list {} | less)"
}

_main "${@}"
exit "${?}"
